import {
	Ai360Icon,
	AlibabaIcon,
	AnthropicIcon,
	BaaiIcon,
	BaichuanIcon,
	BaiduIcon,
	ChatglmIcon,
	CohereIcon,
	DeepseekIcon,
	DefogIcon,
	DoubaoIcon,
	FishaudioIcon,
	GoogleIcon,
	HuggingfaceIcon,
	LingyiwanwuIcon,
	MetaIcon,
	MicrosoftIcon,
	MinimaxIcon,
	MistralIcon,
	MoonshotIcon,
	NeteaseIcon,
	NexusflowIcon,
	OpenaiIcon,
	OpenchatIcon,
	StabilityaiIcon,
	StepfunIcon,
	StreamlakeIcon,
	TencentIcon,
	UnknownIcon,
	XunfeiIcon,
} from '@/assets/aiproxy-models';
import type { InlinedSvgData } from '@/libs/types';

export const AIPROXY_OWNER_ICONS = {
	ai360: Ai360Icon,
	alibaba: AlibabaIcon,
	anthropic: AnthropicIcon,
	baai: BaaiIcon,
	baichuan: BaichuanIcon,
	baidu: BaiduIcon,
	chatglm: ChatglmIcon,
	cohere: CohereIcon,
	deepseek: DeepseekIcon,
	defog: DefogIcon,
	doubao: DoubaoIcon,
	fishaudio: FishaudioIcon,
	funaudiollm: AlibabaIcon,
	google: GoogleIcon,
	huggingface: HuggingfaceIcon,
	jina: UnknownIcon,
	lingyiwanwu: LingyiwanwuIcon,
	meta: MetaIcon,
	microsoft: MicrosoftIcon,
	minimax: MinimaxIcon,
	mistral: MistralIcon,
	moonshot: MoonshotIcon,
	netease: NeteaseIcon,
	nexusflow: NexusflowIcon,
	openai: OpenaiIcon,
	openchat: OpenchatIcon,
	stabilityai: StabilityaiIcon,
	stepfun: StepfunIcon,
	streamlake: StreamlakeIcon,
	tencent: TencentIcon,
	unknown: UnknownIcon,
	xunfei: XunfeiIcon,
} as const satisfies Record<string, InlinedSvgData>;

export function getAiproxyOwnerIcon(ownerKey: string) {
	return AIPROXY_OWNER_ICONS[ownerKey as keyof typeof AIPROXY_OWNER_ICONS] ?? UnknownIcon;
}
